services:
  build_humble:
    image: build_diagnostics:humble
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - distro=humble
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 4G
    volumes:
      - ../../diagnostics:/colcon_ws/src/diagnostics:ro
      - ./build_humble:/colcon_ws/build:rw
    command: >
      /bin/bash -c "
        rm -rf build/* &&
        source /opt/ros/humble/setup.bash &&
        rosdep install -y --from-path src/ --ignore-src &&
        colcon build &&
        colcon test &&
        colcon test-result
      "
  build_jazzy:
    image: build_diagnostics:jazzy
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - distro=jazzy
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 4G
    volumes:
      - ../../diagnostics:/colcon_ws/src/diagnostics:ro
      - ./build_jazzy:/colcon_ws/build:rw
    command: >
      /bin/bash -c "
        rm -rf build/* &&
        source /opt/ros/jazzy/setup.bash &&
        rosdep install -y --from-path src/ --ignore-src &&
        colcon build &&
        colcon test &&
        colcon test-result
      "
  build_kilted:
    image: build_diagnostics:kilted
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - distro=kilted
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 4G
    volumes:
      - ../../diagnostics:/colcon_ws/src/diagnostics:ro
      - ./build_kilted:/colcon_ws/build:rw
    command: >
      /bin/bash -c "
        rm -rf build/* &&
        source /opt/ros/kilted/setup.bash &&
        rosdep install -y --from-path src/ --ignore-src &&
        colcon build &&
        colcon test &&
        colcon test-result
      "
  build_rolling:
    image: build_diagnostics:rolling
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - distro=rolling
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 8G
    volumes:
      - ../../diagnostics:/colcon_ws/src/diagnostics:ro
      - ./build_rolling:/colcon_ws/build:rw
    command: >
      /bin/bash -c "
        rm -rf build/* &&
        source /opt/ros/rolling/setup.bash &&
        rosdep install -y --from-path src/ --ignore-src &&
        colcon build &&
        colcon test &&
        colcon test-result
      "
