services:
  build_humble:
    image: build_diagnostics:humble
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - distro=humble
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 4G
    volumes:
      - ../../diagnostics:/colcon_ws/src/diagnostics:ro
      - ./build_humble:/colcon_ws/build:rw
    command: /bin/bash -c "rm -rf build/* && source /opt/ros/humble/setup.bash && colcon build && colcon test && colcon test-result"
  build_iron:
    image: build_diagnostics:iron
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - distro=iron
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 4G
    volumes:
      - ../../diagnostics:/colcon_ws/src/diagnostics:ro
      - ./build_iron:/colcon_ws/build:rw
    command: /bin/bash -c "rm -rf build/* && source /opt/ros/iron/setup.bash && colcon build && colcon test && colcon test-result"
  build_jazzy:
    image: build_diagnostics:jazzy
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - distro=jazzy
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 4G
    volumes:
      - ../../diagnostics:/colcon_ws/src/diagnostics:ro
      - ./build_jazzy:/colcon_ws/build:rw
    command: /bin/bash -c "rm -rf build/* && source /opt/ros/jazzy/setup.bash && colcon build && colcon test && colcon test-result"
  build_rolling:
    image: build_diagnostics:rolling
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - distro=rolling
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 4G
    volumes:
      - ../../diagnostics:/colcon_ws/src/diagnostics:ro
      - ./build_rolling:/colcon_ws/build:rw
    command: /bin/bash -c "rm -rf build/* && source /opt/ros/rolling/setup.bash && colcon build && colcon test && colcon test-result"
