services:
  build_foxy:
    image: build_diagnostics:foxy
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - distro=foxy
    volumes:
      - ../../diagnostics:/colcon_ws/src/diagnostics:ro
      - ./build_foxy:/colcon_ws/build:rw
    command: /bin/bash -c "rm -rf build/* && source /opt/ros/foxy/setup.bash && colcon build && colcon test && colcon test-result"
  build_humble:
    image: build_diagnostics:humble
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - distro=humble
    volumes:
      - ../../diagnostics:/colcon_ws/src/diagnostics:ro
      - ./build_humble:/colcon_ws/build:rw
    command: /bin/bash -c "rm -rf build/* && source /opt/ros/humble/setup.bash && colcon build && colcon test && colcon test-result"
  build_rolling:
    image: build_diagnostics:rolling
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - distro=rolling
    volumes:
      - ../../diagnostics:/colcon_ws/src/diagnostics:ro
      - ./build_rolling:/colcon_ws/build:rw
    command: /bin/bash -c "rm -rf build/* && source /opt/ros/rolling/setup.bash && colcon build && colcon test && colcon test-result"
