x-build-defaults: &build-defaults
  context: .
  dockerfile: Dockerfile

x-deploy-defaults: &deploy-defaults
  resources:
    limits:
      memory: 4G
    reservations:
      memory: 4G

x-command: &command >
  /bin/bash -c "
    rm -rf build/* &&
    source /opt/ros/$$DISTRO/setup.bash &&
    rosdep install -y --from-path src/ --ignore-src &&
    colcon build --cmake-args -DCMAKE_CXX_FLAGS="-Werror" &&
    colcon test &&
    colcon test-result
  "

services:
  build_humble:
    image: build_diagnostics:humble
    build:
      <<: *build-defaults
      args:
        - distro=humble
    deploy: *deploy-defaults
    environment:
      - DISTRO=humble
    volumes:
      - ../../diagnostics:/colcon_ws/src/diagnostics:ro
      - ./humble_build:/colcon_ws/build:rw
      - ./humble_log:/colcon_ws/log:rw
    command: *command
  build_jazzy:
    image: build_diagnostics:jazzy
    build:
      <<: *build-defaults
      args:
        - distro=jazzy
    deploy: *deploy-defaults
    environment:
      - DISTRO=jazzy
    volumes:
      - ../../diagnostics:/colcon_ws/src/diagnostics:ro
      - ./jazzy_build:/colcon_ws/build:rw
      - ./jazzy_log:/colcon_ws/log:rw
    command: *command
  build_kilted:
    image: build_diagnostics:kilted
    build:
      <<: *build-defaults
      args:
        - distro=kilted
    deploy: *deploy-defaults
    environment:
      - DISTRO=kilted
    volumes:
      - ../../diagnostics:/colcon_ws/src/diagnostics:ro
      - ./kilted_build:/colcon_ws/build:rw
      - ./kilted_log:/colcon_ws/log:rw
    command: *command
  build_rolling:
    image: build_diagnostics:rolling
    build:
      <<: *build-defaults
      args:
        - distro=rolling
    deploy: *deploy-defaults
    environment:
      - DISTRO=rolling
    volumes:
      - ../../diagnostics:/colcon_ws/src/diagnostics:ro
      - ./rolling_build:/colcon_ws/build:rw
      - ./rolling_log:/colcon_ws/log:rw
    command: *command
